# Week 05

## Numpy

In [ ]:
# Numerical arrays
import numpy as np

Next prompt is copied from:
https://numpy.org/doc/2.2/user/absolute_beginners.html

In [1]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape

NameError: name 'np' is not defined

### Multidimensional Homogeneous Arrays

In [ ]:
# is called multimension because have a list in a list or morte
# like following
t = [
    [
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ],
    [
        [9,0],[1,2]
    ]
]

In [ ]:
# so it's possible access 3 levels.
# the full list, then a list inside, then another list.
print (t)
print (t[0])
print (t[0][1])

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 0], [1, 2]]]
[[1, 2], [3, 4]]
[3, 4]


In [ ]:
# A 2D array of intergers.
X = np.array([[1, 2, 3,2], [4, 5, 6,5]])

print (X)

[[1 2 3 2]
 [4 5 6 5]]


In [ ]:
# Number of dimensions.
print (X.ndim)

2


In [ ]:
# Shape of the array.
print (X.shape)

(2, 4)


In [ ]:
# Type of elements.
print (X.dtype)

int64


### Operations

In [ ]:
#Two arrays.
A = np.array ([[1,2], [3,4]])
B = np.array ([[5,6],[7,8]])

# show
print ('A:')
print (A)
print ('B:')
print (B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [ ]:
# Adding constants.
A + 3

# It adds the number to all numbers in the list

array([[4, 5],
       [6, 7]])

In [ ]:
# Adding two arrays
A + B

array([[ 6,  8],
       [10, 12]])

In [ ]:
# Multiplying two arrays.
A * B

array([[ 5, 12],
       [21, 32]])

In [ ]:
# Matrix multiplication
A @ B

array([[19, 22],
       [43, 50]])

### Accessing Elements

In [ ]:
# Recall A.
A

array([[1, 2],
       [3, 4]])

In [ ]:
# Zeroth row, first column
A[0,1]

np.int64(2)

In [ ]:
# First row
A[0]

array([1, 2])

In [ ]:
# First Column
A[:,1]

array([2, 4])

In [ ]:
# An array with lots of elements

X = np.arange(10,21, 3)

# in the round brackets has a structure.
# The fisrt number "10" is the **starting point**
# The second "21" is **finishing point**
# And the third "3" is the **step** (three by three)

print(X)

[10 13 16 19]


In [ ]:
# An array with lots of elements
X = np.arange(21)

print (X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# How to apply the "Starting, ending, step points"
# E.g
# # The first five elementes.
X[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# The next five elements.
X[5:10]

array([5, 6, 7, 8, 9])

In [ ]:
# Every second element.
print (X[0:len(X):2])

# Same function, diferent writing.
# Every second element.
print (X[::2])

[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0  2  4  6  8 10 12 14 16 18 20]


In [ ]:
# The elements from index 5 up.
X[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])